"use client";

import {Metadata} from "next";
import Menu from "@/components/layout/menu";
import "@/styles/globals.css";
import React from 'react';
import {
    QueryClient,
    QueryClientProvider,
    useQuery,
} from 'react-query';

// export const metadata: Metadata = {
//     title: {
//         absolute: "",
//         default: "Rosena Online Shop",
//         template: "%s | Rosena"
//     },
//     description: 'Generated by Next.js',
// }

const queryClient = new QueryClient();

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <QueryClientProvider client={queryClient}>
            <html lang="en">
            <body>
            <header><Menu/></header>
            <main >
                {children}
            </main>
            </body>
            </html>
        </QueryClientProvider>
    )
}

// <section className="flex min-h-screen flex-col items-center justify-between p-24">
//     <div className=" w-full items-center justify-between font-mono text-sm lg:flex">
