import {Metadata} from "next";
import Menu from "@/components/layout/menu";
import "@/styles/globals.css";

export const metadata:Metadata = {
  title: {
    absolute: "",
    default: "Rosena Online Shop",
    template: "%s | Rosena"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header><Menu /></header>
        <main>{children}</main>
      </body>
    </html>
  )
}
